version: '3.1'

services:
  db:
    build: .
    container_name: devtraining-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=devtraining
      - MYSQL_ROOT_PASSWORD=docker
