version: '3.1'

services:
  db:
    image: mysql:8.0
    build: .
    container_name: devtraining-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=devtraining
      - MYSQL_ROOT_PASSWORD=docker
    hostname: danrley

  dbtest:
    image: mysql:8.0
    build: .
    container_name: test-db
    restart: always
    ports:
      - 5433:3306
    environment:
      - MYSQL_DATABASE=devtraining
      - MYSQL_ROOT_PASSWORD=docker
    hostname: danrley
